---
title: "Check-in 1"
subtitle: "ECON 345"
author: "Name: ________________"
output: pdf_document
header-includes:
    # Sans-serif font
    - \renewcommand{\familydefault}{\sfdefault} 
    # Set up page numbering
    - \usepackage{lastpage}
    - \usepackage{fancyhdr}
    - \pagestyle{fancy}
    - \cfoot{Page \thepage\ of \pageref{LastPage}}
    - \renewcommand{\headrulewidth}{0pt} 
---

\thispagestyle{fancy}


#### 1. Please tell us (a) how your name is pronounced, (b) your gender pronouns, and (c) what name we should use if you prefer not to use the name in your official enrollment records. 

```

```

#### 2.	What time zone are you attending class from?

```

```
#### 3.	What kind of internet access will you be using for class? For example, cable internet; dial-up; mobile hotspot; internet accessed outside your home (ie, library), etc.

```

```
#### 4.	What is your level of experience with programming in general? Have you used any statistical programming languages before?

```

```
#### 5.	What is your level of familiarity with econometrics?

```

```
#### 6.	We will be scheduling weekly office hours multiple times a week that most students are available.  Please select all options that will work your schedule? 


| When       |         | Options   |         |
|:----------:|---------|:---------:|---------|
| Mondays    | Morning | Afternoon | Evening |
| Tuesdays   | Morning | Afternoon | Evening |
| Wednesdays | Morning | Afternoon | Evening |
| Thursdays  | Morning | Afternoon | Evening |
| Friday     | | After Class | |
| Pre-Scheduled | | 1-on-1 | |

```

```
#### 7.	Optional: is there anything else you would like the instructors to know about you? 



