---
output:
  pdf_document: default
  html_document: default
---

## How will you be evaluated in this course?

* Project: 65%
    * Status updates: 20%
    * First draft, presentation, final draft: 45%
* Homework assignments: 20%
* Quizzes: 10%
    * Graded check-ins at the beginning of *every* class
    * No exams!
* Communication, Timeliness, & Professionalism: 5%
    * A full grade reduction if you miss two scheduled meetings with your mentor without giving them advanced notice (usually 1 business day)
    * In-Class participation
    * Use respectful and professional language when communicating with course staff.    
* **NOTE**: review the late submission policy


## Academic Integrity

Per the [Spelman College Academic Integrity Policy](https://www.spelman.edu/docs/deans/academic-integrity-policy.pdf) we expect that you will:

* Work collaboratively on assignments but that each person will
do their own write-up of the solutions.
    * When working as a group: each person should think and work through each question. 
    * Do not divide and conquer!
* Cite all your sources on your project; and that everything you write,
even if it is just a summary of another paper, will be in your own
words.



## How can you get help in this course?

Learning a new programming language takes time. We provide as much support as possible.

* [Canvas](https://canvas.instructure.com/courses/6006441), the primary source for information
    * Read the ["How to ask a question" handout](https://canvas.instructure.com/courses/6006441/pages/how-to-ask-a-question) on Canvas
    * Post questions on the discussion boards
    * View Announcements
    * Download Lecture slides, Homework, Handouts
    * Review feedback when grades are posted
    * If you haven't already, create an account and enroll via
https://canvas.instructure.com/courses/10046805. 
<!-- Use the code **CF6XJT** -->
* Office hours (1-on-1 coaching and support)
* Send an email to: \href{mailto:econ345.spelman@gmail.com}{\nolinkurl{econ345.spelman@gmail.com}}
* Talk to your economist advisor for questions about your hands-on project 

**Note: Atlanta Fed staff are only available during business hours**


## How can you help yourself in this course?

* Growth mindset, Iterative approach
    * *"Fail as quickly as possible, learn from it and move on" - Hadley Wickham*
* Built-in R documentation (more on this later)  
* Course textbook: [R for Data Science](http://r4ds.had.co.nz/) - r4ds.had.co.nz
* Reference ['Cheat Sheets'](https://posit.co/resources/cheatsheets/) - https://posit.co/resources/cheatsheets/
* **Google** 
    + "R [error message]"
    + "R [thing you want to do]"
    + "R [package or function name]"
* **ChatGPT**


## Remember, data analysis is a process...

and there's actually no such thing as a "failure" or a "wrong answer"!

* Thinking critically about your code and your output is what gets you to the next step in the iterative process
* Remember, just because your code runs does NOT mean that it is correct
* An attempt will always get you at least partial credit
* An explanation of your thought process well get you more credit
* **Not attempting at all is the only reason you'll get a zero**


## How do students describe this course?

* "It is both a course teaching the technical skill of R programming, as well as a practical lesson on how to conduct research." 

* "The course is really a great opportunity to practice data analysis from start to finish... Question, data, cleaning, analysis, presentation, write up. Other courses offer opportunities to write papers or do some segment of the process, but not the entire thing, and not with the regular practice."

* "I really liked the attention and support that I got from the lecturers, the RA's and other economists. It was intimidating at first but I got comfortable over time and I saw how my performance improved when I took advantage of all the help that was available to me."

## What you should expect for the course
* This course is extremely rewarding, but it will take effort.

* From the feedback we've received from students in past semesters, regarding the **effort, time** and **difficulty** of this course, we **require (much) more than that of the average class**. 

* This information is not to discourage you, but to align your expectations with what we've gathered from students that have previously taken this class.

## What advice would past students give...

1. **GO TO OFFICE HOURS**
2. Start the homework as soon as class ends
3. Don't wait until Thursday to do the homework
4. Go over the slides and homework before class and take notes, so that the time spent in class could be used to reinforce the information that was already read at home. It will also give you the opportunity to ask more questions in class

