## Plot the unemployment rate 

We want to plot the unemployment rate as a number between 0 and 1

* Does this variable exist in the data already? 
* How should it be computed?

## Create a new variable

Use the `mutate` function: 
```{r, echo = TRUE}
# Add a new variable to unemp_df data frame
unemp_df <- mutate(unemp_df, pct_unemp = Unrate/100)
```


## Confirm the result

```{r echo = TRUE}
# Take a look at the changes
head(unemp_df) 
```


## Start with an empty plot

```{r echo = TRUE, fig.align = "center"}
#| echo: true
#| fig-height: 3
#| fig-width: 12
#| out-width: 100%
#| out-height: 55%


ggplot(data = unemp_df)
```

##  Define the x and y axis

```{r}
#| echo: true
#| fig-height: 3
#| fig-width: 12
#| out-width: 100%
#| out-height: 55%


ggplot(data = unemp_df, 
       mapping = aes(x = Year, y = pct_unemp))
```

## Add a line to the plot

```{r}
#| echo: true
#| fig-height: 3
#| fig-width: 12
#| out-width: 100%
#| out-height: 55%


ggplot(data = unemp_df, 
       mapping = aes(x = Year, y= pct_unemp)) +
  geom_line()
```

## Continue adding to the plot...\footnote{More about ggplot2: https://r4ds.had.co.nz/data-visualisation.html} 

```{r}
#| echo: true
#| fig-height: 3
#| fig-width: 12
#| out-width: 100%
#| out-height: 55%


ggplot(data = unemp_df) +
  geom_line(mapping = aes(x = Year, y = pct_unemp), color = "forestgreen") +
  labs(x = "Date", y = "Rate of Unemployment", title = "Unemployment rate over time") +
  theme(legend.title = element_blank())
```




